### ISSUE TITLE
NanoCSS struggles with @supports and @media

### ISSUE THREAD

**Issue by h3nn3s** [arminlinzbauer/gulpex#22]
When using @supports rules inside a @media query, NanoCSS struggles and kills the outer media query and results in completly wrong CSS declarations. This seems to be a bug in NanoCSS Package.

Quickfix: Do not make use of NanoCSS for a while since this bug is fixed.

**Comment by arminlinzbauer** [comment]
Seems to be the case. We should try to make use of the Sass compiler's minification engine instead.

**Comment by h3nn3s** [comment]
Works quite well with your latest fixes in 1.0.2-beta.1
